### ISSUE TITLE
[Question] Why not use ProtocolLib?

### ISSUE THREAD

**Issue by A248** [MinecraftLibraries/TabLib#1]
I just noticed that you forked this repository. However, I'm wondering why you don't want to depend on ProtocolLib. It seems unnecessary to mess with packets yourself. Is there something I'm missing?

By the way, I spent considerable time finding the best tablist API for my own uses. I applied some changes to in a [fork](https://github.com/Arim-Minecraft/tabbed). Later I decided to combine tabbed's skin fetcher with [ProtocolTab](https://github.com/Arim-Minecraft/ProtocolTab), creating a lightweight, thread safe tablist. If you are planning on developing your fork further feel free to take a look at these.

**Comment by JitseB** [comment]
Ah! Good question. I don’t really develop plugins and libraries for the same reason most Minecraft developers do.
I study Applied Physics, which in itself is about really all about problem solving in all sorts of different context. In the past years, when I was still *active* (depending on how your define active, here I mean playing the game) in the Minecraft community, I felt a great need for libraries such as NPCLib, but also for a library that could generate an arena for minigame (WorldLib) and one that could control the tab. These libraries could then be used in a modular sense to create the minigame API, that is GameLib.
Now, back to your question, It boils down to that I really like reverse engineering. NMS can be just that, figuring out which packets that need to be sent, in what order and containing which payload. I think it’s just fun not to have ProtocolLib as a dependency. It gives me a challenge.
In a broader sense, I do agree with you that the practicality of this is not that great. I think most servers nowadays have ProtocolLib installed on their server.
I’m not sure if I’ll even ever finish my TabLib fork, but it was just something for me to pass the time. 😛

**Comment by JitseB** [comment]
I do like your fork, you did some great work on that. Good job!

**Comment by A248** [comment]
Awesome. Anything is worth the challenge
